// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.56.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// KwarantineAPIController binds http requests to an api service and writes the service results to the http response
type KwarantineAPIController struct {
	service KwarantineAPIServicer
	errorHandler ErrorHandler
}

// KwarantineAPIOption for how the controller is set up.
type KwarantineAPIOption func(*KwarantineAPIController)

// WithKwarantineAPIErrorHandler inject ErrorHandler into controller
func WithKwarantineAPIErrorHandler(h ErrorHandler) KwarantineAPIOption {
	return func(c *KwarantineAPIController) {
		c.errorHandler = h
	}
}

// NewKwarantineAPIController creates a default api controller
func NewKwarantineAPIController(s KwarantineAPIServicer, opts ...KwarantineAPIOption) *KwarantineAPIController {
	controller := &KwarantineAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the KwarantineAPIController
func (c *KwarantineAPIController) Routes() Routes {
	return Routes{
		"ListKwarantines": Route{
			"ListKwarantines",
			strings.ToUpper("Get"),
			"/api/v1/kwarantine",
			c.ListKwarantines,
		},
		"ReadKwarantine": Route{
			"ReadKwarantine",
			strings.ToUpper("Get"),
			"/api/v1/kwarantine/{kwarantineId}",
			c.ReadKwarantine,
		},
		"UpdateKwarantine": Route{
			"UpdateKwarantine",
			strings.ToUpper("Put"),
			"/api/v1/kwarantine/{kwarantineId}",
			c.UpdateKwarantine,
		},
		"DeleteKwarantine": Route{
			"DeleteKwarantine",
			strings.ToUpper("Delete"),
			"/api/v1/kwarantine/{kwarantineId}",
			c.DeleteKwarantine,
		},
		"AddKwarantineInstance": Route{
			"AddKwarantineInstance",
			strings.ToUpper("Put"),
			"/api/v1/kwarantine/{kwarantineId}/instance/{instanceId}",
			c.AddKwarantineInstance,
		},
		"RemoveKwarantineInstance": Route{
			"RemoveKwarantineInstance",
			strings.ToUpper("Delete"),
			"/api/v1/kwarantine/{kwarantineId}/instance/{instanceId}",
			c.RemoveKwarantineInstance,
		},
		"AddKwarantineKompute": Route{
			"AddKwarantineKompute",
			strings.ToUpper("Put"),
			"/api/v1/kwarantine/{kwarantineId}/kompute/{komputeId}",
			c.AddKwarantineKompute,
		},
		"RemoveKwarantineKompute": Route{
			"RemoveKwarantineKompute",
			strings.ToUpper("Delete"),
			"/api/v1/kwarantine/{kwarantineId}/kompute/{komputeId}",
			c.RemoveKwarantineKompute,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the KwarantineAPIController
func (c *KwarantineAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ListKwarantines",
			strings.ToUpper("Get"),
			"/api/v1/kwarantine",
			c.ListKwarantines,
		},
		Route{
			"ReadKwarantine",
			strings.ToUpper("Get"),
			"/api/v1/kwarantine/{kwarantineId}",
			c.ReadKwarantine,
		},
		Route{
			"UpdateKwarantine",
			strings.ToUpper("Put"),
			"/api/v1/kwarantine/{kwarantineId}",
			c.UpdateKwarantine,
		},
		Route{
			"DeleteKwarantine",
			strings.ToUpper("Delete"),
			"/api/v1/kwarantine/{kwarantineId}",
			c.DeleteKwarantine,
		},
		Route{
			"AddKwarantineInstance",
			strings.ToUpper("Put"),
			"/api/v1/kwarantine/{kwarantineId}/instance/{instanceId}",
			c.AddKwarantineInstance,
		},
		Route{
			"RemoveKwarantineInstance",
			strings.ToUpper("Delete"),
			"/api/v1/kwarantine/{kwarantineId}/instance/{instanceId}",
			c.RemoveKwarantineInstance,
		},
		Route{
			"AddKwarantineKompute",
			strings.ToUpper("Put"),
			"/api/v1/kwarantine/{kwarantineId}/kompute/{komputeId}",
			c.AddKwarantineKompute,
		},
		Route{
			"RemoveKwarantineKompute",
			strings.ToUpper("Delete"),
			"/api/v1/kwarantine/{kwarantineId}/kompute/{komputeId}",
			c.RemoveKwarantineKompute,
		},
	}
}



// ListKwarantines -
func (c *KwarantineAPIController) ListKwarantines(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ListKwarantines(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ReadKwarantine -
func (c *KwarantineAPIController) ReadKwarantine(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	result, err := c.service.ReadKwarantine(r.Context(), kwarantineIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateKwarantine -
func (c *KwarantineAPIController) UpdateKwarantine(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	var kwarantineParam Kwarantine
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&kwarantineParam); err != nil {
		var requiredErr *RequiredError
		if errors.As(err, &requiredErr) {
			c.errorHandler(w, r, err, nil)
			return
		}
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertKwarantineRequired(kwarantineParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertKwarantineConstraints(kwarantineParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateKwarantine(r.Context(), kwarantineIdParam, kwarantineParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteKwarantine -
func (c *KwarantineAPIController) DeleteKwarantine(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	result, err := c.service.DeleteKwarantine(r.Context(), kwarantineIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// AddKwarantineInstance -
func (c *KwarantineAPIController) AddKwarantineInstance(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	instanceIdParam := params["instanceId"]
	if instanceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"instanceId"}, nil)
		return
	}
	result, err := c.service.AddKwarantineInstance(r.Context(), kwarantineIdParam, instanceIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RemoveKwarantineInstance -
func (c *KwarantineAPIController) RemoveKwarantineInstance(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	instanceIdParam := params["instanceId"]
	if instanceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"instanceId"}, nil)
		return
	}
	result, err := c.service.RemoveKwarantineInstance(r.Context(), kwarantineIdParam, instanceIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// AddKwarantineKompute -
func (c *KwarantineAPIController) AddKwarantineKompute(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	komputeIdParam := params["komputeId"]
	if komputeIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"komputeId"}, nil)
		return
	}
	result, err := c.service.AddKwarantineKompute(r.Context(), kwarantineIdParam, komputeIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RemoveKwarantineKompute -
func (c *KwarantineAPIController) RemoveKwarantineKompute(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	kwarantineIdParam := params["kwarantineId"]
	if kwarantineIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"kwarantineId"}, nil)
		return
	}
	komputeIdParam := params["komputeId"]
	if komputeIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"komputeId"}, nil)
		return
	}
	result, err := c.service.RemoveKwarantineKompute(r.Context(), kwarantineIdParam, komputeIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
