// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Konvey - A Kowabunga Konvey is a layer-4 network load-balancer used to distribute service requests to associated backend instances.
type Konvey struct {

	// The Konvey (Kowabunga Network Load-Balancer) ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Konvey (Kowabunga Network Load-Balancer) name.
	Name string `json:"name,omitempty"`

	// The Konvey (Kowabunga Network Load-Balancer) description.
	Description string `json:"description,omitempty"`

	// The Konvey (Kowabunga Network Load-Balancer) assigned private virtual IP address (read-only).
	Vip string `json:"vip,omitempty"`

	// Whether Konvey (Kowabunga Network Load-Balancer) must be deployed in a highly-available replicated state to support service failover.
	Failover bool `json:"failover,omitempty"`

	// The Konvey (Kowabunga Network Load-Balancer) list of load-balanced endpoints.
	Endpoints []KonveyEndpoint `json:"endpoints"`
}
// UnmarshalJSON validates required property keys then unmarshals into Konvey
func (o *Konvey) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"endpoints",
	}

	requiredNullableProperties := map[string]bool{
		"endpoints": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"vip": {},
		"failover": {},
		"endpoints": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Konvey

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["vip"]; exists {
		if err = json.Unmarshal(value, &decoded.Vip); err != nil {
			return err
		}
	}
	if value, exists := allProperties["failover"]; exists {
		if err = json.Unmarshal(value, &decoded.Failover); err != nil {
			return err
		}
	}
	if value, exists := allProperties["endpoints"]; exists {
		if err = json.Unmarshal(value, &decoded.Endpoints); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKonveyRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKonveyRequired(obj Konvey) error {
	elements := map[string]interface{}{
		"endpoints": obj.Endpoints,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Endpoints {
		if err := AssertKonveyEndpointRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKonveyConstraints checks if the values respects the defined constraints
func AssertKonveyConstraints(obj Konvey) error {
	for _, el := range obj.Endpoints {
		if err := AssertKonveyEndpointConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
