// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// RegionSubnet - A region/subnet map.
type RegionSubnet struct {

	// The region key.
	Key string `json:"key,omitempty"`

	// The subnet ID.
	Value string `json:"value,omitempty"`
}

// AssertRegionSubnetRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertRegionSubnetRequired(obj RegionSubnet) error {
	return nil
}

// AssertRegionSubnetConstraints checks if the values respects the defined constraints
func AssertRegionSubnetConstraints(obj RegionSubnet) error {
	return nil
}
