// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.57.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KMotionPlanRequest - A virtual machine instance kMotion plan request.
type KMotionPlanRequest struct {

	// How the destination Kaktus computing node must be elected. Use \"manual\" to explicitly target a given node (see kaktus), \"zone\" to automatically elect the least busy node within the instance own availability zone, \"region\" to automatically elect the least busy node anywhere within the instance region, or \"auto\" to let Kowabunga fully decide the best possible destination across the region, regardless of the number of availability zones it contains.
	Destination string `json:"destination,omitempty"`

	// The explicit target Kaktus computing node ID to kMotion the instance to. Only used (and required) when destination is set to manual.
	Kaktus string `json:"kaktus,omitempty"`

	// Whether the kMotion must be performed live, without any service interruption, or the instance can instead be shutdown and restarted on its new host.
	Live bool `json:"live,omitempty"`
}

// AssertKMotionPlanRequestRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKMotionPlanRequestRequired(obj KMotionPlanRequest) error {
	return nil
}

// AssertKMotionPlanRequestConstraints checks if the values respects the defined constraints
func AssertKMotionPlanRequestConstraints(obj KMotionPlanRequest) error {
	return nil
}
