// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.56.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Kwarantine - A Kwarantine is an anti-affinity mechanism that ensures its member virtual machine instances or Kompute resources are never co-scheduled on the same Kaktus computing node (host policy) or the same availability zone (zone policy), regardless of Kaktus host scheduling score, so that critical redundant resources stay properly spread out.
type Kwarantine struct {

	// The Kwarantine ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kwarantine name.
	Name string `json:"name"`

	// The Kwarantine description.
	Description string `json:"description,omitempty"`

	// The anti-affinity enforcement policy. Use \"host\" to guarantee no two group members are ever scheduled on the same Kaktus computing node, or \"zone\" to guarantee no two group members are ever scheduled within the same availability zone.
	Policy string `json:"policy,omitempty"`

	// A list of existing virtual machine instance IDs that are part of the Kwarantine group. Members are guaranteed to never be co-scheduled according to the group policy, regardless of Kaktus host scheduling score.
	Instances []string `json:"instances,omitempty"`

	// A list of existing Kompute IDs that are part of the Kwarantine group. Members are guaranteed to never be co-scheduled according to the group policy, regardless of Kaktus host scheduling score.
	Komputes []string `json:"komputes,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into Kwarantine
func (o *Kwarantine) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"policy": {},
		"instances": {},
		"komputes": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Kwarantine

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["policy"]; exists {
		if err = json.Unmarshal(value, &decoded.Policy); err != nil {
			return err
		}
	}
	if value, exists := allProperties["instances"]; exists {
		if err = json.Unmarshal(value, &decoded.Instances); err != nil {
			return err
		}
	}
	if value, exists := allProperties["komputes"]; exists {
		if err = json.Unmarshal(value, &decoded.Komputes); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKwarantineRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKwarantineRequired(obj Kwarantine) error {
	return nil
}

// AssertKwarantineConstraints checks if the values respects the defined constraints
func AssertKwarantineConstraints(obj Kwarantine) error {
	return nil
}
