// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Volume - A storage volume.
type Volume struct {

	// The storage volume ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The storage volume name.
	Name string `json:"name"`

	// The storage volume description.
	Description string `json:"description,omitempty"`

	// The storage volume type.
	Type string `json:"type"`

	// The storage volume size (in bytes).
	Size int64 `json:"size"`
}
// UnmarshalJSON validates required property keys then unmarshals into Volume
func (o *Volume) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"type",
		"size",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"type": false,
		"size": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"type": {},
		"size": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Volume

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["type"]; exists {
		if err = json.Unmarshal(value, &decoded.Type); err != nil {
			return err
		}
	}
	if value, exists := allProperties["size"]; exists {
		if err = json.Unmarshal(value, &decoded.Size); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertVolumeRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertVolumeRequired(obj Volume) error {
	return nil
}

// AssertVolumeConstraints checks if the values respects the defined constraints
func AssertVolumeConstraints(obj Volume) error {
	return nil
}
