// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Password - A user plain-text password.
type Password struct {

	// The plain-text password.
	Value string `json:"value"`
}
// UnmarshalJSON validates required property keys then unmarshals into Password
func (o *Password) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"value",
	}

	requiredNullableProperties := map[string]bool{
		"value": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"value": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Password

	if value, exists := allProperties["value"]; exists {
		if err = json.Unmarshal(value, &decoded.Value); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertPasswordRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertPasswordRequired(obj Password) error {
	return nil
}

// AssertPasswordConstraints checks if the values respects the defined constraints
func AssertPasswordConstraints(obj Password) error {
	return nil
}
