// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Adapter - A network adapter.
type Adapter struct {

	// The network adapter ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The network adapter name.
	Name string `json:"name"`

	// The network adapter description.
	Description string `json:"description,omitempty"`

	// The network adapter hardware address (e.g. 00:11:22:33:44:55). Auto-generated if unspecified.
	Mac string `json:"mac,omitempty"`

	// The network adapter list of associated IPv4 addresses.
	Addresses []string `json:"addresses,omitempty"`

	// The network adapter is a reserved adapter (e.g. router), where the same hardware address can be reused over several subnets.
	Reserved bool `json:"reserved,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into Adapter
func (o *Adapter) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"mac": {},
		"addresses": {},
		"reserved": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Adapter

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["mac"]; exists {
		if err = json.Unmarshal(value, &decoded.Mac); err != nil {
			return err
		}
	}
	if value, exists := allProperties["addresses"]; exists {
		if err = json.Unmarshal(value, &decoded.Addresses); err != nil {
			return err
		}
	}
	if value, exists := allProperties["reserved"]; exists {
		if err = json.Unmarshal(value, &decoded.Reserved); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertAdapterRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertAdapterRequired(obj Adapter) error {
	return nil
}

// AssertAdapterConstraints checks if the values respects the defined constraints
func AssertAdapterConstraints(obj Adapter) error {
	return nil
}
