// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Subnet - A network subnet.
type Subnet struct {

	// The network subnet ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The network subnet name.
	Name string `json:"name"`

	// The network subnet description.
	Description string `json:"description,omitempty"`

	// The network subnet CIDR (e.g. 192.168.0.0/24).
	Cidr string `json:"cidr"`

	// The network subnet router/gateway IP address (e.g. 192.168.0.254).
	Gateway string `json:"gateway"`

	// The network subnet DNS server IP address (gateway value if unspecified).
	Dns string `json:"dns,omitempty"`

	// The list of extra routes to be access through designated gateway (format is 10.0.0.0/8).
	ExtraRoutes []string `json:"extra_routes,omitempty"`

	// The network subnet reserved IPv4 ranges (i.e. no IP address can be assigned from there).
	Reserved []IpRange `json:"reserved,omitempty"`

	// The network subnet IPv4 ranges reserved for per-zone local network gateways (range size must be at least equal to region number of zones).
	GwPool []IpRange `json:"gw_pool,omitempty"`

	// Optional application service type.
	Application string `json:"application,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into Subnet
func (o *Subnet) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"cidr",
		"gateway",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"cidr": false,
		"gateway": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"cidr": {},
		"gateway": {},
		"dns": {},
		"extra_routes": {},
		"reserved": {},
		"gw_pool": {},
		"application": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Subnet

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["cidr"]; exists {
		if err = json.Unmarshal(value, &decoded.Cidr); err != nil {
			return err
		}
	}
	if value, exists := allProperties["gateway"]; exists {
		if err = json.Unmarshal(value, &decoded.Gateway); err != nil {
			return err
		}
	}
	if value, exists := allProperties["dns"]; exists {
		if err = json.Unmarshal(value, &decoded.Dns); err != nil {
			return err
		}
	}
	if value, exists := allProperties["extra_routes"]; exists {
		if err = json.Unmarshal(value, &decoded.ExtraRoutes); err != nil {
			return err
		}
	}
	if value, exists := allProperties["reserved"]; exists {
		if err = json.Unmarshal(value, &decoded.Reserved); err != nil {
			return err
		}
	}
	if value, exists := allProperties["gw_pool"]; exists {
		if err = json.Unmarshal(value, &decoded.GwPool); err != nil {
			return err
		}
	}
	if value, exists := allProperties["application"]; exists {
		if err = json.Unmarshal(value, &decoded.Application); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertSubnetRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertSubnetRequired(obj Subnet) error {
	for _, el := range obj.Reserved {
		if err := AssertIpRangeRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.GwPool {
		if err := AssertIpRangeRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSubnetConstraints checks if the values respects the defined constraints
func AssertSubnetConstraints(obj Subnet) error {
	for _, el := range obj.Reserved {
		if err := AssertIpRangeConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.GwPool {
		if err := AssertIpRangeConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
