// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KonveyEndpoint - A Konvey Endpoint Service settings.
type KonveyEndpoint struct {

	// The Konvey (Kowabunga Network Load-Balancer) endpoint name.
	Name string `json:"name"`

	// The port to be exposed.
	Port int64 `json:"port"`

	// The transport layer protocol to be exposed.
	Protocol string `json:"protocol"`

	// The Konvey (Kowabunga Network Load-Balancer) list of load-balanced backends.
	Backends KonveyBackends `json:"backends"`
}
// UnmarshalJSON validates required property keys then unmarshals into KonveyEndpoint
func (o *KonveyEndpoint) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"port",
		"protocol",
		"backends",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"port": false,
		"protocol": false,
		"backends": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"name": {},
		"port": {},
		"protocol": {},
		"backends": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KonveyEndpoint

	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["port"]; exists {
		if err = json.Unmarshal(value, &decoded.Port); err != nil {
			return err
		}
	}
	if value, exists := allProperties["protocol"]; exists {
		if err = json.Unmarshal(value, &decoded.Protocol); err != nil {
			return err
		}
	}
	if value, exists := allProperties["backends"]; exists {
		if err = json.Unmarshal(value, &decoded.Backends); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKonveyEndpointRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKonveyEndpointRequired(obj KonveyEndpoint) error {
	elements := map[string]interface{}{
		"backends": obj.Backends,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertKonveyBackendsRequired(obj.Backends); err != nil {
		return err
	}
	return nil
}

// AssertKonveyEndpointConstraints checks if the values respects the defined constraints
func AssertKonveyEndpointConstraints(obj KonveyEndpoint) error {
	if err := AssertKonveyBackendsConstraints(obj.Backends); err != nil {
		return err
	}
	return nil
}
