// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KonveyBackends - A Konvey Backends settings.
type KonveyBackends struct {

	// The Konvey (Kowabunga Network Load-Balancer) endpoint list of load-balanced backend hosts.
	Hosts []string `json:"hosts"`

	// The Konvey (Kowabunga Network Load-Balancer) endpoint backend service port.
	Port int64 `json:"port"`
}
// UnmarshalJSON validates required property keys then unmarshals into KonveyBackends
func (o *KonveyBackends) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"hosts",
		"port",
	}

	requiredNullableProperties := map[string]bool{
		"hosts": false,
		"port": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"hosts": {},
		"port": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KonveyBackends

	if value, exists := allProperties["hosts"]; exists {
		if err = json.Unmarshal(value, &decoded.Hosts); err != nil {
			return err
		}
	}
	if value, exists := allProperties["port"]; exists {
		if err = json.Unmarshal(value, &decoded.Port); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKonveyBackendsRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKonveyBackendsRequired(obj KonveyBackends) error {
	elements := map[string]interface{}{
		"hosts": obj.Hosts,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKonveyBackendsConstraints checks if the values respects the defined constraints
func AssertKonveyBackendsConstraints(obj KonveyBackends) error {
	return nil
}
