// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// User - A Kowabunga user.
type User struct {

	// The Kowabunga user ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kowabunga user name.
	Name string `json:"name"`

	// The Kowabunga user description.
	Description string `json:"description,omitempty"`

	// User email address.
	Email string `json:"email"`

	// The Kowabunga user role.
	Role string `json:"role"`

	// Whether or not to receive email notifications on events.
	Notifications bool `json:"notifications,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into User
func (o *User) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"email",
		"role",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"email": false,
		"role": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"email": {},
		"role": {},
		"notifications": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded User

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["email"]; exists {
		if err = json.Unmarshal(value, &decoded.Email); err != nil {
			return err
		}
	}
	if value, exists := allProperties["role"]; exists {
		if err = json.Unmarshal(value, &decoded.Role); err != nil {
			return err
		}
	}
	if value, exists := allProperties["notifications"]; exists {
		if err = json.Unmarshal(value, &decoded.Notifications); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertUserRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertUserRequired(obj User) error {
	return nil
}

// AssertUserConstraints checks if the values respects the defined constraints
func AssertUserConstraints(obj User) error {
	return nil
}
