// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Metadata - A key/value metadata.
type Metadata struct {

	// The metadata key.
	Key string `json:"key"`

	// The metadata value.
	Value string `json:"value"`
}
// UnmarshalJSON validates required property keys then unmarshals into Metadata
func (o *Metadata) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"key",
		"value",
	}

	requiredNullableProperties := map[string]bool{
		"key": false,
		"value": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"key": {},
		"value": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Metadata

	if value, exists := allProperties["key"]; exists {
		if err = json.Unmarshal(value, &decoded.Key); err != nil {
			return err
		}
	}
	if value, exists := allProperties["value"]; exists {
		if err = json.Unmarshal(value, &decoded.Value); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertMetadataRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertMetadataRequired(obj Metadata) error {
	return nil
}

// AssertMetadataConstraints checks if the values respects the defined constraints
func AssertMetadataConstraints(obj Metadata) error {
	return nil
}
