// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// InstanceRemoteAccess - A virtual machine instance remote access characteristics.
type InstanceRemoteAccess struct {

	// The virtual machine instance remote access URL.
	Url string `json:"url"`
}
// UnmarshalJSON validates required property keys then unmarshals into InstanceRemoteAccess
func (o *InstanceRemoteAccess) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"url",
	}

	requiredNullableProperties := map[string]bool{
		"url": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"url": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded InstanceRemoteAccess

	if value, exists := allProperties["url"]; exists {
		if err = json.Unmarshal(value, &decoded.Url); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertInstanceRemoteAccessRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertInstanceRemoteAccessRequired(obj InstanceRemoteAccess) error {
	return nil
}

// AssertInstanceRemoteAccessConstraints checks if the values respects the defined constraints
func AssertInstanceRemoteAccessConstraints(obj InstanceRemoteAccess) error {
	return nil
}
