// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// InstanceState - A virtual machine instance state.
type InstanceState struct {

	// The virtual machine instance state.
	State string `json:"state"`

	// The virtual machine instance reason of the state.
	Reason string `json:"reason"`
}
// UnmarshalJSON validates required property keys then unmarshals into InstanceState
func (o *InstanceState) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"state",
		"reason",
	}

	requiredNullableProperties := map[string]bool{
		"state": false,
		"reason": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"state": {},
		"reason": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded InstanceState

	if value, exists := allProperties["state"]; exists {
		if err = json.Unmarshal(value, &decoded.State); err != nil {
			return err
		}
	}
	if value, exists := allProperties["reason"]; exists {
		if err = json.Unmarshal(value, &decoded.Reason); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertInstanceStateRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertInstanceStateRequired(obj InstanceState) error {
	return nil
}

// AssertInstanceStateConstraints checks if the values respects the defined constraints
func AssertInstanceStateConstraints(obj InstanceState) error {
	return nil
}
