// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.57.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KMotionCommitRequest - A virtual machine instance kMotion commit request.
type KMotionCommitRequest struct {

	// The ID of the previously computed kMotion plan (see kMotion plan webservice) to execute.
	Plan string `json:"plan"`
}
// UnmarshalJSON validates required property keys then unmarshals into KMotionCommitRequest
func (o *KMotionCommitRequest) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"plan",
	}

	requiredNullableProperties := map[string]bool{
		"plan": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"plan": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KMotionCommitRequest

	if value, exists := allProperties["plan"]; exists {
		if err = json.Unmarshal(value, &decoded.Plan); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKMotionCommitRequestRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKMotionCommitRequestRequired(obj KMotionCommitRequest) error {
	return nil
}

// AssertKMotionCommitRequestConstraints checks if the values respects the defined constraints
func AssertKMotionCommitRequestConstraints(obj KMotionCommitRequest) error {
	return nil
}
