// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// StorageNfs - A NFS storage.
type StorageNfs struct {

	// The NFS storage ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The NFS storage name.
	Name string `json:"name"`

	// The NFS storage description.
	Description string `json:"description,omitempty"`

	// The associated NFS endpoint FQDN.
	Endpoint string `json:"endpoint"`

	// The underlying associated Ceph volume name.
	Fs string `json:"fs,omitempty"`

	// List of NFS Ganesha API server IP addresses.
	Backends []string `json:"backends,omitempty"`

	// NFS Ganesha API server port (default 54934).
	Port int64 `json:"port,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into StorageNfs
func (o *StorageNfs) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"endpoint",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"endpoint": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"endpoint": {},
		"fs": {},
		"backends": {},
		"port": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded StorageNfs

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["endpoint"]; exists {
		if err = json.Unmarshal(value, &decoded.Endpoint); err != nil {
			return err
		}
	}
	if value, exists := allProperties["fs"]; exists {
		if err = json.Unmarshal(value, &decoded.Fs); err != nil {
			return err
		}
	}
	if value, exists := allProperties["backends"]; exists {
		if err = json.Unmarshal(value, &decoded.Backends); err != nil {
			return err
		}
	}
	if value, exists := allProperties["port"]; exists {
		if err = json.Unmarshal(value, &decoded.Port); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertStorageNfsRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertStorageNfsRequired(obj StorageNfs) error {
	return nil
}

// AssertStorageNfsConstraints checks if the values respects the defined constraints
func AssertStorageNfsConstraints(obj StorageNfs) error {
	return nil
}
