// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Kylo - A Kylo provides an elastic NFS-like remote storage volume.
type Kylo struct {

	// The Kylo ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kylo name.
	Name string `json:"name"`

	// The Kylo description.
	Description string `json:"description,omitempty"`

	// The Kylo volume access type.
	Access string `json:"access,omitempty"`

	// The Kylo NFS protocol versions to be supported.
	Protocols []int32 `json:"protocols,omitempty"`

	// The Kylo endpoint FQDN (read-only).
	Endpoint string `json:"endpoint,omitempty"`

	// The Kylo volume bytes used (read-only).
	Size int64 `json:"size,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into Kylo
func (o *Kylo) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"access": {},
		"protocols": {},
		"endpoint": {},
		"size": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Kylo

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["access"]; exists {
		if err = json.Unmarshal(value, &decoded.Access); err != nil {
			return err
		}
	}
	if value, exists := allProperties["protocols"]; exists {
		if err = json.Unmarshal(value, &decoded.Protocols); err != nil {
			return err
		}
	}
	if value, exists := allProperties["endpoint"]; exists {
		if err = json.Unmarshal(value, &decoded.Endpoint); err != nil {
			return err
		}
	}
	if value, exists := allProperties["size"]; exists {
		if err = json.Unmarshal(value, &decoded.Size); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKyloRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKyloRequired(obj Kylo) error {
	return nil
}

// AssertKyloConstraints checks if the values respects the defined constraints
func AssertKyloConstraints(obj Kylo) error {
	return nil
}
