// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KawaiiNetIp - A Kawaii Network IP settings.
type KawaiiNetIp struct {

	// The Kawaii global public gateways virtual IP addresses (read-only).
	Public []string `json:"public"`

	// The Kawaii global private gateways virtual IP addresses (read-only).
	Private []string `json:"private"`

	// The Kawaii per-zone list of Kowabunga virtual IP addresses.
	Zones []KawaiiNetIpZone `json:"zones"`
}
// UnmarshalJSON validates required property keys then unmarshals into KawaiiNetIp
func (o *KawaiiNetIp) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"public",
		"private",
		"zones",
	}

	requiredNullableProperties := map[string]bool{
		"public": false,
		"private": false,
		"zones": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"public": {},
		"private": {},
		"zones": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KawaiiNetIp

	if value, exists := allProperties["public"]; exists {
		if err = json.Unmarshal(value, &decoded.Public); err != nil {
			return err
		}
	}
	if value, exists := allProperties["private"]; exists {
		if err = json.Unmarshal(value, &decoded.Private); err != nil {
			return err
		}
	}
	if value, exists := allProperties["zones"]; exists {
		if err = json.Unmarshal(value, &decoded.Zones); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKawaiiNetIpRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKawaiiNetIpRequired(obj KawaiiNetIp) error {
	elements := map[string]interface{}{
		"public": obj.Public,
		"private": obj.Private,
		"zones": obj.Zones,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Zones {
		if err := AssertKawaiiNetIpZoneRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKawaiiNetIpConstraints checks if the values respects the defined constraints
func AssertKawaiiNetIpConstraints(obj KawaiiNetIp) error {
	for _, el := range obj.Zones {
		if err := AssertKawaiiNetIpZoneConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
