// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Cost - A resource cost.
type Cost struct {

	// The unit price information.
	Price float32 `json:"price"`

	// The associated currency.
	Currency string `json:"currency"`
}
// UnmarshalJSON validates required property keys then unmarshals into Cost
func (o *Cost) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"price",
		"currency",
	}

	requiredNullableProperties := map[string]bool{
		"price": false,
		"currency": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"price": {},
		"currency": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Cost

	if value, exists := allProperties["price"]; exists {
		if err = json.Unmarshal(value, &decoded.Price); err != nil {
			return err
		}
	}
	if value, exists := allProperties["currency"]; exists {
		if err = json.Unmarshal(value, &decoded.Currency); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertCostRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertCostRequired(obj Cost) error {
	return nil
}

// AssertCostConstraints checks if the values respects the defined constraints
func AssertCostConstraints(obj Cost) error {
	return nil
}
