// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// VNet - A virtual network.
type VNet struct {

	// The virtual network ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The virtual network name.
	Name string `json:"name"`

	// The virtual network description.
	Description string `json:"description,omitempty"`

	// The VLAN identifier (0 if unspecified).
	Vlan int64 `json:"vlan,omitempty"`

	// The libvirt's bridge network interface (brX).
	Interface string `json:"interface"`

	// Is the virtual network adapter connected to private (LAN) or public (WAN) physical network ?.
	Private bool `json:"private,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into VNet
func (o *VNet) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"interface",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"interface": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"vlan": {},
		"interface": {},
		"private": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded VNet

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["vlan"]; exists {
		if err = json.Unmarshal(value, &decoded.Vlan); err != nil {
			return err
		}
	}
	if value, exists := allProperties["interface"]; exists {
		if err = json.Unmarshal(value, &decoded.Interface); err != nil {
			return err
		}
	}
	if value, exists := allProperties["private"]; exists {
		if err = json.Unmarshal(value, &decoded.Private); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertVNetRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertVNetRequired(obj VNet) error {
	return nil
}

// AssertVNetConstraints checks if the values respects the defined constraints
func AssertVNetConstraints(obj VNet) error {
	return nil
}
