// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// IpRange - A reserved IPv4 addresses pool range, non-addressable by Kowabunga.
type IpRange struct {

	// The range's first IP address.
	First string `json:"first"`

	// The range's last IP address.
	Last string `json:"last"`
}
// UnmarshalJSON validates required property keys then unmarshals into IpRange
func (o *IpRange) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"first",
		"last",
	}

	requiredNullableProperties := map[string]bool{
		"first": false,
		"last": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"first": {},
		"last": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded IpRange

	if value, exists := allProperties["first"]; exists {
		if err = json.Unmarshal(value, &decoded.First); err != nil {
			return err
		}
	}
	if value, exists := allProperties["last"]; exists {
		if err = json.Unmarshal(value, &decoded.Last); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertIpRangeRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertIpRangeRequired(obj IpRange) error {
	return nil
}

// AssertIpRangeConstraints checks if the values respects the defined constraints
func AssertIpRangeConstraints(obj IpRange) error {
	return nil
}
