// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KawaiiFirewallIngressRule - A Kawaii public firewall ingress rule.
type KawaiiFirewallIngressRule struct {

	// The source IP or CIDR to accept public traffic from.
	Source string `json:"source,omitempty"`

	// The transport layer protocol to accept public traffic from.
	Protocol string `json:"protocol,omitempty"`

	// The port (or list of ports) to accept public traffic from. Ranges are accepted. Format is a-b,c-d (e.g. 443; 22,80,443; 80,443,3000-3005).
	Ports string `json:"ports"`
}
// UnmarshalJSON validates required property keys then unmarshals into KawaiiFirewallIngressRule
func (o *KawaiiFirewallIngressRule) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"ports",
	}

	requiredNullableProperties := map[string]bool{
		"ports": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"source": {},
		"protocol": {},
		"ports": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KawaiiFirewallIngressRule

	if value, exists := allProperties["source"]; exists {
		if err = json.Unmarshal(value, &decoded.Source); err != nil {
			return err
		}
	}
	if value, exists := allProperties["protocol"]; exists {
		if err = json.Unmarshal(value, &decoded.Protocol); err != nil {
			return err
		}
	}
	if value, exists := allProperties["ports"]; exists {
		if err = json.Unmarshal(value, &decoded.Ports); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKawaiiFirewallIngressRuleRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKawaiiFirewallIngressRuleRequired(obj KawaiiFirewallIngressRule) error {
	return nil
}

// AssertKawaiiFirewallIngressRuleConstraints checks if the values respects the defined constraints
func AssertKawaiiFirewallIngressRuleConstraints(obj KawaiiFirewallIngressRule) error {
	return nil
}
