// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// StoragePool - A storage pool.
type StoragePool struct {

	// The storage pool ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The storage pool name.
	Name string `json:"name"`

	// The storage pool description.
	Description string `json:"description,omitempty"`

	// Ceph pool name.
	Pool string `json:"pool"`

	// Ceph Monitor(s) address or FQDN.
	CephAddress string `json:"ceph_address,omitempty"`

	// Ceph Monitor(s) port (default 3300).
	CephPort int64 `json:"ceph_port,omitempty"`

	// The libvirt secret UUID for CephX authentication.
	CephSecretUuid string `json:"ceph_secret_uuid,omitempty"`

	// Cost associated to the storage pool.
	Cost Cost `json:"cost,omitempty"`

	// a list of existing remote agents managing the storage pool.
	Agents []string `json:"agents"`
}
// UnmarshalJSON validates required property keys then unmarshals into StoragePool
func (o *StoragePool) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"pool",
		"agents",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"pool": false,
		"agents": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"pool": {},
		"ceph_address": {},
		"ceph_port": {},
		"ceph_secret_uuid": {},
		"cost": {},
		"agents": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded StoragePool

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["pool"]; exists {
		if err = json.Unmarshal(value, &decoded.Pool); err != nil {
			return err
		}
	}
	if value, exists := allProperties["ceph_address"]; exists {
		if err = json.Unmarshal(value, &decoded.CephAddress); err != nil {
			return err
		}
	}
	if value, exists := allProperties["ceph_port"]; exists {
		if err = json.Unmarshal(value, &decoded.CephPort); err != nil {
			return err
		}
	}
	if value, exists := allProperties["ceph_secret_uuid"]; exists {
		if err = json.Unmarshal(value, &decoded.CephSecretUuid); err != nil {
			return err
		}
	}
	if value, exists := allProperties["cost"]; exists {
		if err = json.Unmarshal(value, &decoded.Cost); err != nil {
			return err
		}
	}
	if value, exists := allProperties["agents"]; exists {
		if err = json.Unmarshal(value, &decoded.Agents); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertStoragePoolRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertStoragePoolRequired(obj StoragePool) error {
	elements := map[string]interface{}{
		"agents": obj.Agents,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCostRequired(obj.Cost); err != nil {
		return err
	}
	return nil
}

// AssertStoragePoolConstraints checks if the values respects the defined constraints
func AssertStoragePoolConstraints(obj StoragePool) error {
	if err := AssertCostConstraints(obj.Cost); err != nil {
		return err
	}
	return nil
}
