// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Project - A Kowabunga project corresponds to a single tenant, isolated set of resources.
type Project struct {

	// The project ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The project name.
	Name string `json:"name"`

	// The project description.
	Description string `json:"description,omitempty"`

	// Internal domain name (e.g. myproject.acme.com).
	Domain string `json:"domain,omitempty"`

	// Default root password, set at cloud-init instance bootstrap phase. Will be randomly auto-generated at each instance creation if unspecified.
	RootPassword string `json:"root_password,omitempty"`

	// Default service user name, created at cloud-init instance bootstrap phase. Will use Kowabunga's default configuration one if unspecified.
	BootstrapUser string `json:"bootstrap_user,omitempty"`

	// Default public SSH key, to be associated to bootstrap user. Will use Kowabunga's default configuration one if unspecified.
	BootstrapPubkey string `json:"bootstrap_pubkey,omitempty"`

	// A list of tags to be associated to the project.
	Tags []string `json:"tags,omitempty"`

	// A list of metadata to be associated to the project.
	Metadatas []Metadata `json:"metadatas,omitempty"`

	// The global project resource quotas (0 for unlimited).
	Quotas ProjectResources `json:"quotas,omitempty"`

	// The assigned project VPC private subnets IDs (read-only).
	PrivateSubnets []RegionSubnet `json:"private_subnets,omitempty"`

	// The list of VRRP IDs used by -as-a-service resources within the project virtual network (read-only). Should your application use VRRP for service redundancy, you should use different IDs to prevent issues..
	ReservedVrrpIds []int32 `json:"reserved_vrrp_ids,omitempty"`

	// A list of user teams allowed to administrate the project (i.e. capable of managing internal resources).
	Teams []string `json:"teams"`

	// A list of Kowabunga regions the project is managing resources from.
	Regions []string `json:"regions"`
}
// UnmarshalJSON validates required property keys then unmarshals into Project
func (o *Project) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"teams",
		"regions",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"teams": false,
		"regions": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"domain": {},
		"root_password": {},
		"bootstrap_user": {},
		"bootstrap_pubkey": {},
		"tags": {},
		"metadatas": {},
		"quotas": {},
		"private_subnets": {},
		"reserved_vrrp_ids": {},
		"teams": {},
		"regions": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Project

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["domain"]; exists {
		if err = json.Unmarshal(value, &decoded.Domain); err != nil {
			return err
		}
	}
	if value, exists := allProperties["root_password"]; exists {
		if err = json.Unmarshal(value, &decoded.RootPassword); err != nil {
			return err
		}
	}
	if value, exists := allProperties["bootstrap_user"]; exists {
		if err = json.Unmarshal(value, &decoded.BootstrapUser); err != nil {
			return err
		}
	}
	if value, exists := allProperties["bootstrap_pubkey"]; exists {
		if err = json.Unmarshal(value, &decoded.BootstrapPubkey); err != nil {
			return err
		}
	}
	if value, exists := allProperties["tags"]; exists {
		if err = json.Unmarshal(value, &decoded.Tags); err != nil {
			return err
		}
	}
	if value, exists := allProperties["metadatas"]; exists {
		if err = json.Unmarshal(value, &decoded.Metadatas); err != nil {
			return err
		}
	}
	if value, exists := allProperties["quotas"]; exists {
		if err = json.Unmarshal(value, &decoded.Quotas); err != nil {
			return err
		}
	}
	if value, exists := allProperties["private_subnets"]; exists {
		if err = json.Unmarshal(value, &decoded.PrivateSubnets); err != nil {
			return err
		}
	}
	if value, exists := allProperties["reserved_vrrp_ids"]; exists {
		if err = json.Unmarshal(value, &decoded.ReservedVrrpIds); err != nil {
			return err
		}
	}
	if value, exists := allProperties["teams"]; exists {
		if err = json.Unmarshal(value, &decoded.Teams); err != nil {
			return err
		}
	}
	if value, exists := allProperties["regions"]; exists {
		if err = json.Unmarshal(value, &decoded.Regions); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertProjectRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertProjectRequired(obj Project) error {
	elements := map[string]interface{}{
		"teams": obj.Teams,
		"regions": obj.Regions,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Metadatas {
		if err := AssertMetadataRequired(el); err != nil {
			return err
		}
	}
	if err := AssertProjectResourcesRequired(obj.Quotas); err != nil {
		return err
	}
	for _, el := range obj.PrivateSubnets {
		if err := AssertRegionSubnetRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertProjectConstraints checks if the values respects the defined constraints
func AssertProjectConstraints(obj Project) error {
	for _, el := range obj.Metadatas {
		if err := AssertMetadataConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertProjectResourcesConstraints(obj.Quotas); err != nil {
		return err
	}
	for _, el := range obj.PrivateSubnets {
		if err := AssertRegionSubnetConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
