// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// DnsRecord - A DNS record.
type DnsRecord struct {

	// The DNS record ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The DNS record name.
	Name string `json:"name"`

	// The DNS record description.
	Description string `json:"description,omitempty"`

	// The DNS record associated domain (inherited from associated project).
	Domain string `json:"domain,omitempty"`

	// A list of IPv4 addresses to be associated to the record.
	Addresses []string `json:"addresses"`
}
// UnmarshalJSON validates required property keys then unmarshals into DnsRecord
func (o *DnsRecord) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"addresses",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"addresses": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"domain": {},
		"addresses": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded DnsRecord

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["domain"]; exists {
		if err = json.Unmarshal(value, &decoded.Domain); err != nil {
			return err
		}
	}
	if value, exists := allProperties["addresses"]; exists {
		if err = json.Unmarshal(value, &decoded.Addresses); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertDnsRecordRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertDnsRecordRequired(obj DnsRecord) error {
	elements := map[string]interface{}{
		"addresses": obj.Addresses,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDnsRecordConstraints checks if the values respects the defined constraints
func AssertDnsRecordConstraints(obj DnsRecord) error {
	return nil
}
