// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.57.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KMotionPlan - A virtual machine instance kMotion plan.
type KMotionPlan struct {

	// The kMotion plan ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The ID of the virtual machine instance this kMotion plan applies to.
	Instance string `json:"instance"`

	// The ID of the Kaktus computing node currently hosting the instance.
	Source string `json:"source"`

	// The ID of the Kaktus computing node elected to host the instance once the kMotion completes.
	Target string `json:"target"`

	// Whether the plan is for a live kMotion, without any service interruption, or the instance will be shutdown and restarted on its new host.
	Live bool `json:"live"`
}
// UnmarshalJSON validates required property keys then unmarshals into KMotionPlan
func (o *KMotionPlan) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"instance",
		"source",
		"target",
		"live",
	}

	requiredNullableProperties := map[string]bool{
		"instance": false,
		"source": false,
		"target": false,
		"live": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"instance": {},
		"source": {},
		"target": {},
		"live": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KMotionPlan

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["instance"]; exists {
		if err = json.Unmarshal(value, &decoded.Instance); err != nil {
			return err
		}
	}
	if value, exists := allProperties["source"]; exists {
		if err = json.Unmarshal(value, &decoded.Source); err != nil {
			return err
		}
	}
	if value, exists := allProperties["target"]; exists {
		if err = json.Unmarshal(value, &decoded.Target); err != nil {
			return err
		}
	}
	if value, exists := allProperties["live"]; exists {
		if err = json.Unmarshal(value, &decoded.Live); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKMotionPlanRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKMotionPlanRequired(obj KMotionPlan) error {
	return nil
}

// AssertKMotionPlanConstraints checks if the values respects the defined constraints
func AssertKMotionPlanConstraints(obj KMotionPlan) error {
	return nil
}
