// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



type ApiErrorConflict struct {

	Status int32 `json:"status"`

	Error string `json:"error"`

	Reason string `json:"reason"`
}
// UnmarshalJSON validates required property keys then unmarshals into ApiErrorConflict
func (o *ApiErrorConflict) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"status",
		"error",
		"reason",
	}

	requiredNullableProperties := map[string]bool{
		"status": false,
		"error": false,
		"reason": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"status": {},
		"error": {},
		"reason": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded ApiErrorConflict

	if value, exists := allProperties["status"]; exists {
		if err = json.Unmarshal(value, &decoded.Status); err != nil {
			return err
		}
	}
	if value, exists := allProperties["error"]; exists {
		if err = json.Unmarshal(value, &decoded.Error); err != nil {
			return err
		}
	}
	if value, exists := allProperties["reason"]; exists {
		if err = json.Unmarshal(value, &decoded.Reason); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertApiErrorConflictRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertApiErrorConflictRequired(obj ApiErrorConflict) error {
	return nil
}

// AssertApiErrorConflictConstraints checks if the values respects the defined constraints
func AssertApiErrorConflictConstraints(obj ApiErrorConflict) error {
	return nil
}
