// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Kaktus - A Kaktus (Kowabunga Affordable KVM and Tight Underneath Storage) is an hyper-converged infrastructure (HCI) bare-metal node offering computing and distributed storage capabilites.
type Kaktus struct {

	// The Kaktus computing node ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kaktus computing node name.
	Name string `json:"name"`

	// The Kaktus computing node description.
	Description string `json:"description,omitempty"`

	// Cost associated to the Kaktus node's CPU resources.
	CpuCost Cost `json:"cpu_cost,omitempty"`

	// Cost associated to the Kaktus node's memory resources.
	MemoryCost Cost `json:"memory_cost,omitempty"`

	// The Kaktus node CPU resource over-commit ratio. Overcommitting CPU resources for VMs means allocating more virtual CPUs (vCPUs) to the virtual machines (VMs) than the physical cores available on the node. This can help optimize the utilization of the node CPU and increase the density of VMs per node.
	OvercommitCpuRatio int64 `json:"overcommit_cpu_ratio,omitempty"`

	// The Kaktus node memory resource over-commit ratio. Memory overcommitment is a concept in computing that covers the assignment of more memory to virtual computing devices (or processes) than the physical machine they are hosted, or running on, actually has.
	OvercommitMemoryRatio int64 `json:"overcommit_memory_ratio,omitempty"`

	// a list of existing remote agents managing the Kaktus node.
	Agents []string `json:"agents"`
}
// UnmarshalJSON validates required property keys then unmarshals into Kaktus
func (o *Kaktus) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"agents",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"agents": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"cpu_cost": {},
		"memory_cost": {},
		"overcommit_cpu_ratio": {},
		"overcommit_memory_ratio": {},
		"agents": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Kaktus

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["cpu_cost"]; exists {
		if err = json.Unmarshal(value, &decoded.CpuCost); err != nil {
			return err
		}
	}
	if value, exists := allProperties["memory_cost"]; exists {
		if err = json.Unmarshal(value, &decoded.MemoryCost); err != nil {
			return err
		}
	}
	if value, exists := allProperties["overcommit_cpu_ratio"]; exists {
		if err = json.Unmarshal(value, &decoded.OvercommitCpuRatio); err != nil {
			return err
		}
	}
	if value, exists := allProperties["overcommit_memory_ratio"]; exists {
		if err = json.Unmarshal(value, &decoded.OvercommitMemoryRatio); err != nil {
			return err
		}
	}
	if value, exists := allProperties["agents"]; exists {
		if err = json.Unmarshal(value, &decoded.Agents); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKaktusRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKaktusRequired(obj Kaktus) error {
	elements := map[string]interface{}{
		"agents": obj.Agents,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCostRequired(obj.CpuCost); err != nil {
		return err
	}
	if err := AssertCostRequired(obj.MemoryCost); err != nil {
		return err
	}
	return nil
}

// AssertKaktusConstraints checks if the values respects the defined constraints
func AssertKaktusConstraints(obj Kaktus) error {
	if err := AssertCostConstraints(obj.CpuCost); err != nil {
		return err
	}
	if err := AssertCostConstraints(obj.MemoryCost); err != nil {
		return err
	}
	return nil
}
