// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Kiwi - A Kiwi (Kowabunga Inner Wan Interface) provides edge-network services..
type Kiwi struct {

	// The Kiwi (Kowabunga Inner Wan Interface) provides edge-network services. ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kiwi (Kowabunga Inner Wan Interface) provides edge-network services. name.
	Name string `json:"name"`

	// The Kiwi (Kowabunga Inner Wan Interface) provides edge-network services. description.
	Description string `json:"description,omitempty"`

	// a list of existing remote agents managing the network gateway.
	Agents []string `json:"agents,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into Kiwi
func (o *Kiwi) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"agents": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Kiwi

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["agents"]; exists {
		if err = json.Unmarshal(value, &decoded.Agents); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKiwiRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKiwiRequired(obj Kiwi) error {
	return nil
}

// AssertKiwiConstraints checks if the values respects the defined constraints
func AssertKiwiConstraints(obj Kiwi) error {
	return nil
}
