// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// KaktusCaps - A Kaktus computing node capability.
type KaktusCaps struct {

	// The Kaktus computing node CPU characteristics.
	Cpu KaktusCpu `json:"cpu"`

	// The Kaktus computing node memory size (bytes).
	Memory int64 `json:"memory"`
}
// UnmarshalJSON validates required property keys then unmarshals into KaktusCaps
func (o *KaktusCaps) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"cpu",
		"memory",
	}

	requiredNullableProperties := map[string]bool{
		"cpu": false,
		"memory": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"cpu": {},
		"memory": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded KaktusCaps

	if value, exists := allProperties["cpu"]; exists {
		if err = json.Unmarshal(value, &decoded.Cpu); err != nil {
			return err
		}
	}
	if value, exists := allProperties["memory"]; exists {
		if err = json.Unmarshal(value, &decoded.Memory); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertKaktusCapsRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertKaktusCapsRequired(obj KaktusCaps) error {
	elements := map[string]interface{}{
		"cpu": obj.Cpu,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertKaktusCpuRequired(obj.Cpu); err != nil {
		return err
	}
	return nil
}

// AssertKaktusCapsConstraints checks if the values respects the defined constraints
func AssertKaktusCapsConstraints(obj KaktusCaps) error {
	if err := AssertKaktusCpuConstraints(obj.Cpu); err != nil {
		return err
	}
	return nil
}
