// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.54.0
 * Contact: maintainers@kowabunga.cloud
 */

package sdk


import (
	"encoding/json"
	"fmt"
)



// Template - A image template.
type Template struct {

	// The image template ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The image template name.
	Name string `json:"name"`

	// The image template description.
	Description string `json:"description,omitempty"`

	// Type of operating system if OS kind (useful to determine cloud-init parameters for instance).
	Os string `json:"os,omitempty"`

	// HTTP(s) source URL of the KVM-ready OS image.
	Source string `json:"source"`
}
// UnmarshalJSON validates required property keys then unmarshals into Template
func (o *Template) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"name",
		"source",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"source": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"os": {},
		"source": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Template

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["os"]; exists {
		if err = json.Unmarshal(value, &decoded.Os); err != nil {
			return err
		}
	}
	if value, exists := allProperties["source"]; exists {
		if err = json.Unmarshal(value, &decoded.Source); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertTemplateRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertTemplateRequired(obj Template) error {
	return nil
}

// AssertTemplateConstraints checks if the values respects the defined constraints
func AssertTemplateConstraints(obj Template) error {
	return nil
}
